#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
from pathlib import Path


DEFAULT_CONTEXT_ROOT = Path("context/lofty_crm")
DEFAULT_OUTPUT = DEFAULT_CONTEXT_ROOT / "LOFTY_CRM_FULL_CONTEXT.md"


def load_json(path: Path):
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def load_jsonl(path: Path) -> list[dict]:
    rows = []
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            if line.strip():
                rows.append(json.loads(line))
    return rows


def main() -> int:
    parser = argparse.ArgumentParser(description="Build a single-file Lofty CRM context bundle.")
    parser.add_argument("--context-root", default=str(DEFAULT_CONTEXT_ROOT), help="Path to a scraped Lofty CRM context folder.")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), help="Path where the combined Markdown bundle will be written.")
    args = parser.parse_args()

    context_root = Path(args.context_root).resolve()
    output_path = Path(args.output).resolve()

    summary = load_json(context_root / "summary.json")
    flow_tree = load_json(context_root / "indexes" / "flow_tree.json")
    page_rows = load_jsonl(context_root / "indexes" / "page_index.jsonl")

    pages_by_module: dict[str, list[dict]] = {}
    for row in page_rows:
        pages_by_module.setdefault(row["module"], []).append(row)

    for rows in pages_by_module.values():
        rows.sort(key=lambda item: (item.get("detail", False), item["label"].lower(), item["route"]))

    parts: list[str] = []
    parts.extend(
        [
            "# Lofty CRM Full Context",
            "",
            "This file consolidates a redacted authenticated Lofty CRM scrape into one upload-friendly reference document.",
            "",
            "It is intended for file uploads to AI tools, not for pasting into one normal chat message.",
            "",
            "## Source Snapshot",
            "",
            f"- Source site: `{summary['source']}`",
            f"- Auth mode: `{summary['auth_mode']}`",
            f"- Redaction mode: `{summary['redaction_mode']}`",
            f"- Captured pages: `{summary['counts']['pages']}`",
            f"- Captured API responses: `{summary['counts']['api_responses']}`",
            f"- Scraped at epoch: `{summary['scraped_at_epoch']}`",
            "",
            "## Module Coverage",
            "",
        ]
    )

    for module in flow_tree.get("modules", []):
        parts.append(f"### {module['module']} ({module['page_count']} pages)")
        parts.append("")
        for page in module["pages"]:
            detail_suffix = " [detail]" if page.get("detail") else ""
            parts.append(f"- {page['label']}{detail_suffix}: `{page['route']}`")
        parts.append("")

    parts.extend(
        [
            "## Full Page Context",
            "",
            "Each page below comes from the redacted per-page Markdown summaries generated by the scraper.",
            "",
        ]
    )

    page_number = 1
    for module in sorted(pages_by_module):
        parts.append(f"## Module: {module}")
        parts.append("")
        for row in pages_by_module[module]:
            markdown_path = context_root / row["markdown_path"]
            content = markdown_path.read_text(encoding="utf-8").strip()
            parts.append(f"### Page {page_number}: {row['label']}")
            parts.append("")
            parts.append(content)
            parts.append("")
            parts.append("---")
            parts.append("")
            page_number += 1

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(parts), encoding="utf-8")

    print(f"Wrote combined CRM context bundle to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
